version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: unless-stopped
    networks:
      - backend
    environment:
      - POSTGRES_PASSWORD=root
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - /opt/docker/databases/postgres/data/:/var/lib/postgresql/data
networks:
  backend:
    external: true