services:
  ac:
    build: .
    container_name: ac
    restart: unless-stopped
    privileged: true
    ports:
      - '8085:8085'
    volumes:
      - /opt/docker/services/ac/data:/data/azerothcore
    networks:
      - home-net
networks:
  home-net:
    external: true