version: '3.9'

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: unless-stopped
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
    volumes:
      - /opt/docker/databases/mysql/conf/:/etc/mysql
      - /opt/docker/databases/mysql/data/:/var/lib/mysql
networks:
  backend:
    external: true