version: '3.9'

services:
  mongo:
    image: mongo:7.0
    container_name: mongo
    restart: unless-stopped
    command: mongod --logpath /dev/null --oplogSize 128 --quiet
    networks:
      - backend
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    ports:
      - "27017:27017"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /opt/docker/databases/mongo/data:/data/db
      - /opt/docker/databases/mongo/dump:/dump
networks:
  backend:
    external: true