version: '3'

services:
  clickhouse-01:
    image: clickhouse/clickhouse-server
    hostname: clickhouse-01
    container_name: clickhouse-01
    restart: unless-stopped
    environment:
      - CLICKHOUSE_USER=root
      - CLICKHOUSE_PASSWORD=root
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
    ports:
      - "9000:9000"
      - "8123:8123"
    volumes:
      - /opt/docker/databases/clickhouse/config/:/etc/clickhouse-server/
      - /opt/docker/databases/clickhouse/data/:/var/lib/clickhouse/
      - /opt/docker/databases/clickhouse/log/:/var/log/clickhouse-server/
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    networks:
      - backend
networks:
  backend:
    external: true