version: '3.9'

networks:
  backend:
    external: true

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - /opt/docker/monitor/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - /opt/docker/monitor/prometheus/data/:/prometheus
    ports:
      - "9090:9090"
    networks:
      - backend
  grafana:
    image: grafana/grafana:9.2.15
    container_name: grafana
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - /opt/docker/monitor/grafana/datasources:/etc/grafana/provisioning/datasources
      - /opt/docker/monitor/grafana/lib/:/var/lib/grafana
    networks:
      - backend
  loki:
    image: grafana/loki:2.7.4
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - /opt/docker/monitor/loki/config/:/etc/loki/
    networks:
      - backend

  promtail:
    image: grafana/promtail:2.7.4
    volumes:
      - /var/log:/var/log
      - /opt/docker/monitor/loki/promtail/:/etc/promtail/
    command: -config.file=/etc/promtail/config.yml
    networks:
      - backend
