version: '3.9'

services:
  nginx:
    image: nginx:1.23
    container_name: nginx
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/opt/docker/gateway/nginx/html:/usr/share/nginx/html"
      - "/opt/docker/gateway/nginx/conf:/etc/nginx"
      - "/var/log/nginx:/var/log/nginx"
    networks:
      - backend
networks:
  backend:
    external: true